# docker-compose.yml
version: '3.12'

networks:
  mynetwork:

services:
  web:
  networks:
      - mynetwork
  deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

      build: .
      ports:
        - "5001:5001"
      environment:
        - FLASK_APP=main.py
        - FLASK_ENV=development
        - DATABASE_CONNECTION=${DATABASE_CONNECTION}

      volumes:
        - .:/code

volumes:
  dbdata: