# docker-compose.yml
version: '3.12'

services:
  web:
    build: .
    ports:
      - "5000:5001"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - DATABASE_CONNECTION=${DATABASE_CONNECTION}

    volumes:
      - .:/code

volumes:
  dbdata: